[*] Start mutation process:
   - targets: factorial.py
   - tests: ts-3-5/test_3-5_0-4_150.py
[*] 4 tests passed:
   - test_3-5_0-4_150 [0.12309 s]
[*] Start mutants generation and execution:
   - [#   1] AOR factorial: 
--------------------------------------------------------------------------------
  14:     
  15:     if n <= 0:
  16:         return 0
  17:     
- 18:     return reduce((lambda x, y: (x * y)), range(1, n + 1))
+ 18:     return reduce((lambda x, y: (x / y)), range(1, n + 1))
--------------------------------------------------------------------------------
[0.14552 s] killed by ts-3-5/test_3-5_0-4_150.py::test_factorial_with_positive_integer

def test_factorial_with_positive_integer():
>       assert factorial(5) == 120
E       AssertionError

ts-3-5/test_3-5_0-4_150.py:15: AssertionError
   - [#   2] AOR factorial: 
--------------------------------------------------------------------------------
  14:     
  15:     if n <= 0:
  16:         return 0
  17:     
- 18:     return reduce((lambda x, y: (x * y)), range(1, n + 1))
+ 18:     return reduce((lambda x, y: (x // y)), range(1, n + 1))
--------------------------------------------------------------------------------
[0.15108 s] killed by ts-3-5/test_3-5_0-4_150.py::test_factorial_with_positive_integer

def test_factorial_with_positive_integer():
>       assert factorial(5) == 120
E       AssertionError

ts-3-5/test_3-5_0-4_150.py:15: AssertionError
   - [#   3] AOR factorial: 
--------------------------------------------------------------------------------
  14:     
  15:     if n <= 0:
  16:         return 0
  17:     
- 18:     return reduce((lambda x, y: (x * y)), range(1, n + 1))
+ 18:     return reduce((lambda x, y: (x ** y)), range(1, n + 1))
--------------------------------------------------------------------------------
[0.15431 s] killed by ts-3-5/test_3-5_0-4_150.py::test_factorial_with_positive_integer

def test_factorial_with_positive_integer():
>       assert factorial(5) == 120
E       AssertionError

ts-3-5/test_3-5_0-4_150.py:15: AssertionError
   - [#   4] AOR factorial: 
--------------------------------------------------------------------------------
  14:     
  15:     if n <= 0:
  16:         return 0
  17:     
- 18:     return reduce((lambda x, y: (x * y)), range(1, n + 1))
+ 18:     return reduce((lambda x, y: (x * y)), range(1, n - 1))
--------------------------------------------------------------------------------
[0.14759 s] killed by ts-3-5/test_3-5_0-4_150.py::test_factorial_with_positive_integer

def test_factorial_with_positive_integer():
>       assert factorial(5) == 120
E       AssertionError

ts-3-5/test_3-5_0-4_150.py:15: AssertionError
   - [#   5] COI factorial: 
--------------------------------------------------------------------------------
  11:         The factorial number for n (n!).  Input
  12:         of 0 or less will output 0.
  13:     '''
  14:     
- 15:     if n <= 0:
+ 15:     if not (n <= 0):
  16:         return 0
  17:     
  18:     return reduce((lambda x, y: (x * y)), range(1, n + 1))
--------------------------------------------------------------------------------
[0.14853 s] incompetent

TypeError: factorial:18: TypeError: reduce() of empty iterable with no initial value

   - [#   6] ROR factorial: 
--------------------------------------------------------------------------------
  11:         The factorial number for n (n!).  Input
  12:         of 0 or less will output 0.
  13:     '''
  14:     
- 15:     if n <= 0:
+ 15:     if n >= 0:
  16:         return 0
  17:     
  18:     return reduce((lambda x, y: (x * y)), range(1, n + 1))
--------------------------------------------------------------------------------
[0.15002 s] killed by ts-3-5/test_3-5_0-4_150.py::test_factorial_with_positive_integer

def test_factorial_with_positive_integer():
>       assert factorial(5) == 120
E       AssertionError

ts-3-5/test_3-5_0-4_150.py:15: AssertionError
   - [#   7] ROR factorial: 
--------------------------------------------------------------------------------
  11:         The factorial number for n (n!).  Input
  12:         of 0 or less will output 0.
  13:     '''
  14:     
- 15:     if n <= 0:
+ 15:     if n < 0:
  16:         return 0
  17:     
  18:     return reduce((lambda x, y: (x * y)), range(1, n + 1))
--------------------------------------------------------------------------------
[0.15592 s] incompetent

TypeError: factorial:18: TypeError: reduce() of empty iterable with no initial value

   - [#   8] SDL factorial: 
--------------------------------------------------------------------------------
  12:         of 0 or less will output 0.
  13:     '''
  14:     
  15:     if n <= 0:
- 16:         return 0
+ 16:         pass
  17:     
  18:     return reduce((lambda x, y: (x * y)), range(1, n + 1))
--------------------------------------------------------------------------------
[0.14138 s] incompetent

TypeError: factorial:18: TypeError: reduce() of empty iterable with no initial value

   - [#   9] SDL factorial: 
--------------------------------------------------------------------------------
  14:     
  15:     if n <= 0:
  16:         return 0
  17:     
- 18:     return reduce((lambda x, y: (x * y)), range(1, n + 1))
+ 18:     pass
--------------------------------------------------------------------------------
[0.14722 s] killed by ts-3-5/test_3-5_0-4_150.py::test_factorial_with_positive_integer

def test_factorial_with_positive_integer():
>       assert factorial(5) == 120
E       AssertionError

ts-3-5/test_3-5_0-4_150.py:15: AssertionError
[*] Mutation score [1.56930 s]: 100.0%
   - all: 9
   - killed: 6 (66.7%)
   - survived: 0 (0.0%)
   - incompetent: 3 (33.3%)
   - timeout: 0 (0.0%)
