[*] Start mutation process:
   - targets: convert_base.py
   - tests: ts-3-5/test_3-5_0-6_185.py
[*] 8 tests passed:
   - test_3-5_0-6_185 [0.18827 s]
[*] Start mutants generation and execution:
   - [#   1] AOD convert_base: 
--------------------------------------------------------------------------------
   1: def convert_base(val: str, base: int):
   2:     if (base < 0 or (base > 10 and base != 16)):
-  3:         return -1
+  3:         return 1
   4:     value = 0
   5:     for (i, digit) in enumerate(val):
   6:         digit_val = convert_digit_to_int(digit)
   7:         if (digit_val < 0 or digit_val > base):
--------------------------------------------------------------------------------
[0.21056 s] killed by ts-3-5/test_3-5_0-6_185.py::test_convert_base_invalid_base

def test_convert_base_invalid_base():
>       assert convert_base("10", -1) == -1
E       AssertionError

ts-3-5/test_3-5_0-6_185.py:15: AssertionError
   - [#   2] AOD convert_base: 
--------------------------------------------------------------------------------
   4:     value = 0
   5:     for (i, digit) in enumerate(val):
   6:         digit_val = convert_digit_to_int(digit)
   7:         if (digit_val < 0 or digit_val > base):
-  8:             return -1
+  8:             return 1
   9:         
  10:         value += digit_val * (base ** ((len(val) - i) - 1))
  11:     return value
  12: 
--------------------------------------------------------------------------------
[0.19296 s] survived
   - [#   3] AOD convert_base: 
--------------------------------------------------------------------------------
  12: 
  13: 
  14: def convert_digit_to_int(char: str):
  15:     if (len(char) != 1 or ord(char) > ord('f')):
- 16:         return -1
+ 16:         return 1
  17:     return int(char, 16)
--------------------------------------------------------------------------------
[0.23135 s] killed by ts-3-5/test_3-5_0-6_185.py::test_convert_digit_to_int_invalid_char

def test_convert_digit_to_int_invalid_char():
>       assert convert_digit_to_int("g") == -1
E       AssertionError

ts-3-5/test_3-5_0-6_185.py:27: AssertionError
   - [#   4] AOR convert_base: 
--------------------------------------------------------------------------------
   1: def convert_base(val: str, base: int):
   2:     if (base < 0 or (base > 10 and base != 16)):
-  3:         return -1
+  3:         return +1
   4:     value = 0
   5:     for (i, digit) in enumerate(val):
   6:         digit_val = convert_digit_to_int(digit)
   7:         if (digit_val < 0 or digit_val > base):
--------------------------------------------------------------------------------
[0.20633 s] killed by ts-3-5/test_3-5_0-6_185.py::test_convert_base_invalid_base

def test_convert_base_invalid_base():
>       assert convert_base("10", -1) == -1
E       AssertionError

ts-3-5/test_3-5_0-6_185.py:15: AssertionError
   - [#   5] AOR convert_base: 
--------------------------------------------------------------------------------
   4:     value = 0
   5:     for (i, digit) in enumerate(val):
   6:         digit_val = convert_digit_to_int(digit)
   7:         if (digit_val < 0 or digit_val > base):
-  8:             return -1
+  8:             return +1
   9:         
  10:         value += digit_val * (base ** ((len(val) - i) - 1))
  11:     return value
  12: 
--------------------------------------------------------------------------------
[0.19180 s] survived
   - [#   6] AOR convert_base: 
--------------------------------------------------------------------------------
   6:         digit_val = convert_digit_to_int(digit)
   7:         if (digit_val < 0 or digit_val > base):
   8:             return -1
   9:         
- 10:         value += digit_val * (base ** ((len(val) - i) - 1))
+ 10:         value += digit_val / (base ** ((len(val) - i) - 1))
  11:     return value
  12: 
  13: 
  14: def convert_digit_to_int(char: str):
--------------------------------------------------------------------------------
[0.20717 s] killed by ts-3-5/test_3-5_0-6_185.py::test_convert_base_valid

def test_convert_base_valid():
>       assert convert_base("10", 2) == 2
E       AssertionError

ts-3-5/test_3-5_0-6_185.py:12: AssertionError
   - [#   7] AOR convert_base: 
--------------------------------------------------------------------------------
   6:         digit_val = convert_digit_to_int(digit)
   7:         if (digit_val < 0 or digit_val > base):
   8:             return -1
   9:         
- 10:         value += digit_val * (base ** ((len(val) - i) - 1))
+ 10:         value += digit_val // (base ** ((len(val) - i) - 1))
  11:     return value
  12: 
  13: 
  14: def convert_digit_to_int(char: str):
--------------------------------------------------------------------------------
[0.19903 s] killed by ts-3-5/test_3-5_0-6_185.py::test_convert_base_valid

def test_convert_base_valid():
>       assert convert_base("10", 2) == 2
E       AssertionError

ts-3-5/test_3-5_0-6_185.py:12: AssertionError
   - [#   8] AOR convert_base: 
--------------------------------------------------------------------------------
   6:         digit_val = convert_digit_to_int(digit)
   7:         if (digit_val < 0 or digit_val > base):
   8:             return -1
   9:         
- 10:         value += digit_val * (base ** ((len(val) - i) - 1))
+ 10:         value += digit_val ** (base ** ((len(val) - i) - 1))
  11:     return value
  12: 
  13: 
  14: def convert_digit_to_int(char: str):
--------------------------------------------------------------------------------
[0.21441 s] killed by ts-3-5/test_3-5_0-6_185.py::test_convert_base_valid

def test_convert_base_valid():
>       assert convert_base("10", 2) == 2
E       AssertionError

ts-3-5/test_3-5_0-6_185.py:12: AssertionError
   - [#   9] AOR convert_base: 
--------------------------------------------------------------------------------
   6:         digit_val = convert_digit_to_int(digit)
   7:         if (digit_val < 0 or digit_val > base):
   8:             return -1
   9:         
- 10:         value += digit_val * (base ** ((len(val) - i) - 1))
+ 10:         value += digit_val * (base * ((len(val) - i) - 1))
  11:     return value
  12: 
  13: 
  14: def convert_digit_to_int(char: str):
--------------------------------------------------------------------------------
[0.21634 s] killed by ts-3-5/test_3-5_0-6_185.py::test_convert_base_invalid_digit

def test_convert_base_invalid_digit():
>       assert convert_base("12", 2) == 4
E       AssertionError

ts-3-5/test_3-5_0-6_185.py:18: AssertionError
   - [#  10] AOR convert_base: 
--------------------------------------------------------------------------------
   6:         digit_val = convert_digit_to_int(digit)
   7:         if (digit_val < 0 or digit_val > base):
   8:             return -1
   9:         
- 10:         value += digit_val * (base ** ((len(val) - i) - 1))
+ 10:         value += digit_val * (base ** ((len(val) + i) - 1))
  11:     return value
  12: 
  13: 
  14: def convert_digit_to_int(char: str):
--------------------------------------------------------------------------------
[0.21947 s] killed by ts-3-5/test_3-5_0-6_185.py::test_convert_base_invalid_digit

def test_convert_base_invalid_digit():
>       assert convert_base("12", 2) == 4
E       AssertionError

ts-3-5/test_3-5_0-6_185.py:18: AssertionError
   - [#  11] AOR convert_base: 
--------------------------------------------------------------------------------
   6:         digit_val = convert_digit_to_int(digit)
   7:         if (digit_val < 0 or digit_val > base):
   8:             return -1
   9:         
- 10:         value += digit_val * (base ** ((len(val) - i) - 1))
+ 10:         value += digit_val * (base ** ((len(val) - i) + 1))
  11:     return value
  12: 
  13: 
  14: def convert_digit_to_int(char: str):
--------------------------------------------------------------------------------
[0.19327 s] killed by ts-3-5/test_3-5_0-6_185.py::test_convert_base_valid

def test_convert_base_valid():
>       assert convert_base("10", 2) == 2
E       AssertionError

ts-3-5/test_3-5_0-6_185.py:12: AssertionError
   - [#  12] AOR convert_base: 
--------------------------------------------------------------------------------
  12: 
  13: 
  14: def convert_digit_to_int(char: str):
  15:     if (len(char) != 1 or ord(char) > ord('f')):
- 16:         return -1
+ 16:         return +1
  17:     return int(char, 16)
--------------------------------------------------------------------------------
[0.20868 s] killed by ts-3-5/test_3-5_0-6_185.py::test_convert_digit_to_int_invalid_char

def test_convert_digit_to_int_invalid_char():
>       assert convert_digit_to_int("g") == -1
E       AssertionError

ts-3-5/test_3-5_0-6_185.py:27: AssertionError
   - [#  13] ASR convert_base: 
--------------------------------------------------------------------------------
   6:         digit_val = convert_digit_to_int(digit)
   7:         if (digit_val < 0 or digit_val > base):
   8:             return -1
   9:         
- 10:         value += digit_val * (base ** ((len(val) - i) - 1))
+ 10:         value -= digit_val * (base ** ((len(val) - i) - 1))
  11:     return value
  12: 
  13: 
  14: def convert_digit_to_int(char: str):
--------------------------------------------------------------------------------
[0.23167 s] killed by ts-3-5/test_3-5_0-6_185.py::test_convert_base_valid

def test_convert_base_valid():
>       assert convert_base("10", 2) == 2
E       AssertionError

ts-3-5/test_3-5_0-6_185.py:12: AssertionError
   - [#  14] COI convert_base: 
--------------------------------------------------------------------------------
   1: def convert_base(val: str, base: int):
-  2:     if (base < 0 or (base > 10 and base != 16)):
+  2:     if not ((base < 0 or (base > 10 and base != 16))):
   3:         return -1
   4:     value = 0
   5:     for (i, digit) in enumerate(val):
   6:         digit_val = convert_digit_to_int(digit)
--------------------------------------------------------------------------------
[0.21845 s] killed by ts-3-5/test_3-5_0-6_185.py::test_convert_base_valid

def test_convert_base_valid():
>       assert convert_base("10", 2) == 2
E       AssertionError

ts-3-5/test_3-5_0-6_185.py:12: AssertionError
   - [#  15] COI convert_base: 
--------------------------------------------------------------------------------
   3:         return -1
   4:     value = 0
   5:     for (i, digit) in enumerate(val):
   6:         digit_val = convert_digit_to_int(digit)
-  7:         if (digit_val < 0 or digit_val > base):
+  7:         if not ((digit_val < 0 or digit_val > base)):
   8:             return -1
   9:         
  10:         value += digit_val * (base ** ((len(val) - i) - 1))
  11:     return value
--------------------------------------------------------------------------------
[0.22409 s] killed by ts-3-5/test_3-5_0-6_185.py::test_convert_base_valid

def test_convert_base_valid():
>       assert convert_base("10", 2) == 2
E       AssertionError

ts-3-5/test_3-5_0-6_185.py:12: AssertionError
   - [#  16] COI convert_base: 
--------------------------------------------------------------------------------
  11:     return value
  12: 
  13: 
  14: def convert_digit_to_int(char: str):
- 15:     if (len(char) != 1 or ord(char) > ord('f')):
+ 15:     if not ((len(char) != 1 or ord(char) > ord('f'))):
  16:         return -1
  17:     return int(char, 16)
--------------------------------------------------------------------------------
[0.19109 s] killed by ts-3-5/test_3-5_0-6_185.py::test_convert_base_valid

def test_convert_base_valid():
>       assert convert_base("10", 2) == 2
E       AssertionError

ts-3-5/test_3-5_0-6_185.py:12: AssertionError
   - [#  17] LCR convert_base: 
--------------------------------------------------------------------------------
   1: def convert_base(val: str, base: int):
-  2:     if (base < 0 or (base > 10 and base != 16)):
+  2:     if (base < 0 and (base > 10 and base != 16)):
   3:         return -1
   4:     value = 0
   5:     for (i, digit) in enumerate(val):
   6:         digit_val = convert_digit_to_int(digit)
--------------------------------------------------------------------------------
[0.18198 s] survived
   - [#  18] LCR convert_base: 
--------------------------------------------------------------------------------
   1: def convert_base(val: str, base: int):
-  2:     if (base < 0 or (base > 10 and base != 16)):
+  2:     if (base < 0 or (base > 10 or base != 16)):
   3:         return -1
   4:     value = 0
   5:     for (i, digit) in enumerate(val):
   6:         digit_val = convert_digit_to_int(digit)
--------------------------------------------------------------------------------
[0.22308 s] killed by ts-3-5/test_3-5_0-6_185.py::test_convert_base_valid

def test_convert_base_valid():
>       assert convert_base("10", 2) == 2
E       AssertionError

ts-3-5/test_3-5_0-6_185.py:12: AssertionError
   - [#  19] LCR convert_base: 
--------------------------------------------------------------------------------
   3:         return -1
   4:     value = 0
   5:     for (i, digit) in enumerate(val):
   6:         digit_val = convert_digit_to_int(digit)
-  7:         if (digit_val < 0 or digit_val > base):
+  7:         if (digit_val < 0 and digit_val > base):
   8:             return -1
   9:         
  10:         value += digit_val * (base ** ((len(val) - i) - 1))
  11:     return value
--------------------------------------------------------------------------------
[0.19587 s] survived
   - [#  20] LCR convert_base: 
--------------------------------------------------------------------------------
  11:     return value
  12: 
  13: 
  14: def convert_digit_to_int(char: str):
- 15:     if (len(char) != 1 or ord(char) > ord('f')):
+ 15:     if (len(char) != 1 and ord(char) > ord('f')):
  16:         return -1
  17:     return int(char, 16)
--------------------------------------------------------------------------------
[0.22933 s] killed by ts-3-5/test_3-5_0-6_185.py::test_convert_digit_to_int_invalid_char

def test_convert_digit_to_int_invalid_char():
>       assert convert_digit_to_int("g") == -1

ts-3-5/test_3-5_0-6_185.py:27: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

char = 'g'

>   ???
E   ValueError: invalid literal for int() with base 16: 'g'

convert_base:17: ValueError
   - [#  21] OIL convert_base: 
--------------------------------------------------------------------------------
   7:         if (digit_val < 0 or digit_val > base):
   8:             return -1
   9:         
  10:         value += digit_val * (base ** ((len(val) - i) - 1))
- 11:     return value
- 12: 
+ 11:         break
+ 12:     return value
  13: 
  14: def convert_digit_to_int(char: str):
  15:     if (len(char) != 1 or ord(char) > ord('f')):
  16:         return -1
--------------------------------------------------------------------------------
[0.21142 s] killed by ts-3-5/test_3-5_0-6_185.py::test_convert_base_invalid_digit

def test_convert_base_invalid_digit():
>       assert convert_base("12", 2) == 4
E       AssertionError

ts-3-5/test_3-5_0-6_185.py:18: AssertionError
   - [#  22] RIL convert_base: 
--------------------------------------------------------------------------------
   1: def convert_base(val: str, base: int):
   2:     if (base < 0 or (base > 10 and base != 16)):
   3:         return -1
   4:     value = 0
-  5:     for (i, digit) in enumerate(val):
+  5:     for (i, digit) in reversed(enumerate(val)):
   6:         digit_val = convert_digit_to_int(digit)
   7:         if (digit_val < 0 or digit_val > base):
   8:             return -1
   9:         
--------------------------------------------------------------------------------
[0.21847 s] incompetent

TypeError: convert_base:5: TypeError: 'enumerate' object is not reversible

   - [#  23] ROR convert_base: 
--------------------------------------------------------------------------------
   1: def convert_base(val: str, base: int):
-  2:     if (base < 0 or (base > 10 and base != 16)):
+  2:     if (base > 0 or (base > 10 and base != 16)):
   3:         return -1
   4:     value = 0
   5:     for (i, digit) in enumerate(val):
   6:         digit_val = convert_digit_to_int(digit)
--------------------------------------------------------------------------------
[0.21256 s] killed by ts-3-5/test_3-5_0-6_185.py::test_convert_base_valid

def test_convert_base_valid():
>       assert convert_base("10", 2) == 2
E       AssertionError

ts-3-5/test_3-5_0-6_185.py:12: AssertionError
   - [#  24] ROR convert_base: 
--------------------------------------------------------------------------------
   1: def convert_base(val: str, base: int):
-  2:     if (base < 0 or (base > 10 and base != 16)):
+  2:     if (base <= 0 or (base > 10 and base != 16)):
   3:         return -1
   4:     value = 0
   5:     for (i, digit) in enumerate(val):
   6:         digit_val = convert_digit_to_int(digit)
--------------------------------------------------------------------------------
[0.18954 s] survived
   - [#  25] ROR convert_base: 
--------------------------------------------------------------------------------
   1: def convert_base(val: str, base: int):
-  2:     if (base < 0 or (base > 10 and base != 16)):
+  2:     if (base < 0 or (base < 10 and base != 16)):
   3:         return -1
   4:     value = 0
   5:     for (i, digit) in enumerate(val):
   6:         digit_val = convert_digit_to_int(digit)
--------------------------------------------------------------------------------
[0.21712 s] killed by ts-3-5/test_3-5_0-6_185.py::test_convert_base_valid

def test_convert_base_valid():
>       assert convert_base("10", 2) == 2
E       AssertionError

ts-3-5/test_3-5_0-6_185.py:12: AssertionError
   - [#  26] ROR convert_base: 
--------------------------------------------------------------------------------
   1: def convert_base(val: str, base: int):
-  2:     if (base < 0 or (base > 10 and base != 16)):
+  2:     if (base < 0 or (base >= 10 and base != 16)):
   3:         return -1
   4:     value = 0
   5:     for (i, digit) in enumerate(val):
   6:         digit_val = convert_digit_to_int(digit)
--------------------------------------------------------------------------------
[0.17577 s] survived
   - [#  27] ROR convert_base: 
--------------------------------------------------------------------------------
   1: def convert_base(val: str, base: int):
-  2:     if (base < 0 or (base > 10 and base != 16)):
+  2:     if (base < 0 or (base > 10 and base == 16)):
   3:         return -1
   4:     value = 0
   5:     for (i, digit) in enumerate(val):
   6:         digit_val = convert_digit_to_int(digit)
--------------------------------------------------------------------------------
[0.21802 s] killed by ts-3-5/test_3-5_0-6_185.py::test_convert_base_hexadecimal

def test_convert_base_hexadecimal():
>       assert convert_base("ff", 16) == 255
E       AssertionError

ts-3-5/test_3-5_0-6_185.py:21: AssertionError
   - [#  28] ROR convert_base: 
--------------------------------------------------------------------------------
   3:         return -1
   4:     value = 0
   5:     for (i, digit) in enumerate(val):
   6:         digit_val = convert_digit_to_int(digit)
-  7:         if (digit_val < 0 or digit_val > base):
+  7:         if (digit_val > 0 or digit_val > base):
   8:             return -1
   9:         
  10:         value += digit_val * (base ** ((len(val) - i) - 1))
  11:     return value
--------------------------------------------------------------------------------
[0.21688 s] killed by ts-3-5/test_3-5_0-6_185.py::test_convert_base_valid

def test_convert_base_valid():
>       assert convert_base("10", 2) == 2
E       AssertionError

ts-3-5/test_3-5_0-6_185.py:12: AssertionError
   - [#  29] ROR convert_base: 
--------------------------------------------------------------------------------
   3:         return -1
   4:     value = 0
   5:     for (i, digit) in enumerate(val):
   6:         digit_val = convert_digit_to_int(digit)
-  7:         if (digit_val < 0 or digit_val > base):
+  7:         if (digit_val <= 0 or digit_val > base):
   8:             return -1
   9:         
  10:         value += digit_val * (base ** ((len(val) - i) - 1))
  11:     return value
--------------------------------------------------------------------------------
[0.19773 s] killed by ts-3-5/test_3-5_0-6_185.py::test_convert_base_valid

def test_convert_base_valid():
>       assert convert_base("10", 2) == 2
E       AssertionError

ts-3-5/test_3-5_0-6_185.py:12: AssertionError
   - [#  30] ROR convert_base: 
--------------------------------------------------------------------------------
   3:         return -1
   4:     value = 0
   5:     for (i, digit) in enumerate(val):
   6:         digit_val = convert_digit_to_int(digit)
-  7:         if (digit_val < 0 or digit_val > base):
+  7:         if (digit_val < 0 or digit_val < base):
   8:             return -1
   9:         
  10:         value += digit_val * (base ** ((len(val) - i) - 1))
  11:     return value
--------------------------------------------------------------------------------
[0.20322 s] killed by ts-3-5/test_3-5_0-6_185.py::test_convert_base_valid

def test_convert_base_valid():
>       assert convert_base("10", 2) == 2
E       AssertionError

ts-3-5/test_3-5_0-6_185.py:12: AssertionError
   - [#  31] ROR convert_base: 
--------------------------------------------------------------------------------
   3:         return -1
   4:     value = 0
   5:     for (i, digit) in enumerate(val):
   6:         digit_val = convert_digit_to_int(digit)
-  7:         if (digit_val < 0 or digit_val > base):
+  7:         if (digit_val < 0 or digit_val >= base):
   8:             return -1
   9:         
  10:         value += digit_val * (base ** ((len(val) - i) - 1))
  11:     return value
--------------------------------------------------------------------------------
[0.20002 s] killed by ts-3-5/test_3-5_0-6_185.py::test_convert_base_invalid_digit

def test_convert_base_invalid_digit():
>       assert convert_base("12", 2) == 4
E       AssertionError

ts-3-5/test_3-5_0-6_185.py:18: AssertionError
   - [#  32] ROR convert_base: 
--------------------------------------------------------------------------------
  11:     return value
  12: 
  13: 
  14: def convert_digit_to_int(char: str):
- 15:     if (len(char) != 1 or ord(char) > ord('f')):
+ 15:     if (len(char) == 1 or ord(char) > ord('f')):
  16:         return -1
  17:     return int(char, 16)
--------------------------------------------------------------------------------
[0.20198 s] killed by ts-3-5/test_3-5_0-6_185.py::test_convert_base_valid

def test_convert_base_valid():
>       assert convert_base("10", 2) == 2
E       AssertionError

ts-3-5/test_3-5_0-6_185.py:12: AssertionError
   - [#  33] ROR convert_base: 
--------------------------------------------------------------------------------
  11:     return value
  12: 
  13: 
  14: def convert_digit_to_int(char: str):
- 15:     if (len(char) != 1 or ord(char) > ord('f')):
+ 15:     if (len(char) != 1 or ord(char) < ord('f')):
  16:         return -1
  17:     return int(char, 16)
--------------------------------------------------------------------------------
[0.21392 s] killed by ts-3-5/test_3-5_0-6_185.py::test_convert_base_valid

def test_convert_base_valid():
>       assert convert_base("10", 2) == 2
E       AssertionError

ts-3-5/test_3-5_0-6_185.py:12: AssertionError
   - [#  34] ROR convert_base: 
--------------------------------------------------------------------------------
  11:     return value
  12: 
  13: 
  14: def convert_digit_to_int(char: str):
- 15:     if (len(char) != 1 or ord(char) > ord('f')):
+ 15:     if (len(char) != 1 or ord(char) >= ord('f')):
  16:         return -1
  17:     return int(char, 16)
--------------------------------------------------------------------------------
[0.19963 s] killed by ts-3-5/test_3-5_0-6_185.py::test_convert_base_hexadecimal

def test_convert_base_hexadecimal():
>       assert convert_base("ff", 16) == 255
E       AssertionError

ts-3-5/test_3-5_0-6_185.py:21: AssertionError
   - [#  35] SDL convert_base: 
--------------------------------------------------------------------------------
   1: def convert_base(val: str, base: int):
   2:     if (base < 0 or (base > 10 and base != 16)):
-  3:         return -1
+  3:         pass
   4:     value = 0
   5:     for (i, digit) in enumerate(val):
   6:         digit_val = convert_digit_to_int(digit)
   7:         if (digit_val < 0 or digit_val > base):
--------------------------------------------------------------------------------
[0.19291 s] survived
   - [#  36] SDL convert_base: 
--------------------------------------------------------------------------------
   1: def convert_base(val: str, base: int):
   2:     if (base < 0 or (base > 10 and base != 16)):
   3:         return -1
-  4:     value = 0
+  4:     pass
   5:     for (i, digit) in enumerate(val):
   6:         digit_val = convert_digit_to_int(digit)
   7:         if (digit_val < 0 or digit_val > base):
   8:             return -1
--------------------------------------------------------------------------------
[0.19416 s] killed by ts-3-5/test_3-5_0-6_185.py::test_convert_base_valid

def test_convert_base_valid():
>       assert convert_base("10", 2) == 2

ts-3-5/test_3-5_0-6_185.py:12: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

val = '10', base = 2

>   ???
E   UnboundLocalError: local variable 'value' referenced before assignment

convert_base:10: UnboundLocalError
   - [#  37] SDL convert_base: 
--------------------------------------------------------------------------------
   2:     if (base < 0 or (base > 10 and base != 16)):
   3:         return -1
   4:     value = 0
   5:     for (i, digit) in enumerate(val):
-  6:         digit_val = convert_digit_to_int(digit)
+  6:         pass
   7:         if (digit_val < 0 or digit_val > base):
   8:             return -1
   9:         
  10:         value += digit_val * (base ** ((len(val) - i) - 1))
--------------------------------------------------------------------------------
[0.20341 s] killed by ts-3-5/test_3-5_0-6_185.py::test_convert_base_valid

def test_convert_base_valid():
>       assert convert_base("10", 2) == 2

ts-3-5/test_3-5_0-6_185.py:12: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

val = '10', base = 2

>   ???
E   NameError: name 'digit_val' is not defined

convert_base:7: NameError
   - [#  38] SDL convert_base: 
--------------------------------------------------------------------------------
   4:     value = 0
   5:     for (i, digit) in enumerate(val):
   6:         digit_val = convert_digit_to_int(digit)
   7:         if (digit_val < 0 or digit_val > base):
-  8:             return -1
+  8:             pass
   9:         
  10:         value += digit_val * (base ** ((len(val) - i) - 1))
  11:     return value
  12: 
--------------------------------------------------------------------------------
[0.18286 s] survived
   - [#  39] SDL convert_base: 
--------------------------------------------------------------------------------
   7:         if (digit_val < 0 or digit_val > base):
   8:             return -1
   9:         
  10:         value += digit_val * (base ** ((len(val) - i) - 1))
- 11:     return value
+ 11:     pass
  12: 
  13: 
  14: def convert_digit_to_int(char: str):
  15:     if (len(char) != 1 or ord(char) > ord('f')):
--------------------------------------------------------------------------------
[0.19688 s] killed by ts-3-5/test_3-5_0-6_185.py::test_convert_base_valid

def test_convert_base_valid():
>       assert convert_base("10", 2) == 2
E       AssertionError

ts-3-5/test_3-5_0-6_185.py:12: AssertionError
   - [#  40] SDL convert_base: 
--------------------------------------------------------------------------------
  12: 
  13: 
  14: def convert_digit_to_int(char: str):
  15:     if (len(char) != 1 or ord(char) > ord('f')):
- 16:         return -1
+ 16:         pass
  17:     return int(char, 16)
--------------------------------------------------------------------------------
[0.20910 s] killed by ts-3-5/test_3-5_0-6_185.py::test_convert_digit_to_int_invalid_char

def test_convert_digit_to_int_invalid_char():
>       assert convert_digit_to_int("g") == -1

ts-3-5/test_3-5_0-6_185.py:27: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

char = 'g'

>   ???
E   ValueError: invalid literal for int() with base 16: 'g'

convert_base:17: ValueError
   - [#  41] SDL convert_base: 
--------------------------------------------------------------------------------
  13: 
  14: def convert_digit_to_int(char: str):
  15:     if (len(char) != 1 or ord(char) > ord('f')):
  16:         return -1
- 17:     return int(char, 16)
+ 17:     pass
--------------------------------------------------------------------------------
[0.19902 s] incompetent

TypeError: convert_base:7: TypeError: '<' not supported between instances of 'NoneType' and 'int'

   - [#  42] ZIL convert_base: 
--------------------------------------------------------------------------------
   2:     if (base < 0 or (base > 10 and base != 16)):
   3:         return -1
   4:     value = 0
   5:     for (i, digit) in enumerate(val):
-  6:         digit_val = convert_digit_to_int(digit)
-  7:         if (digit_val < 0 or digit_val > base):
-  8:             return -1
-  9:         
- 10:         value += digit_val * (base ** ((len(val) - i) - 1))
+  6:         break
+  7:     
+  8:     
+  9:     
+ 10:     
  11:     return value
  12: 
  13: 
  14: def convert_digit_to_int(char: str):
--------------------------------------------------------------------------------
[0.20195 s] killed by ts-3-5/test_3-5_0-6_185.py::test_convert_base_valid

def test_convert_base_valid():
>       assert convert_base("10", 2) == 2
E       AssertionError

ts-3-5/test_3-5_0-6_185.py:12: AssertionError
[*] Mutation score [9.49746 s]: 80.0%
   - all: 42
   - killed: 32 (76.2%)
   - survived: 8 (19.0%)
   - incompetent: 2 (4.8%)
   - timeout: 0 (0.0%)
